/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    post: operations["AuthController_register"];
  };
  "/auth/login": {
    post: operations["AuthController_login"];
  };
  "/auth/refresh": {
    post: operations["AuthController_refresh"];
  };
  "/auth/logout": {
    post: operations["AuthController_logout"];
  };
  "/auth/verify-email": {
    post: operations["AuthController_verifyEmail"];
  };
  "/auth/resend-verification": {
    post: operations["AuthController_resend"];
  };
  "/users/me": {
    get: operations["UsersController_me"];
  };
  "/vendors/apply": {
    post: operations["VendorsController_apply"];
  };
  "/vendor/products": {
    get: operations["VendorsController_listProducts"];
    post: operations["VendorsController_createProduct"];
  };
  "/vendor/products/{id}": {
    patch: operations["VendorsController_updateProduct"];
  };
  "/vendor/products/{id}/variants": {
    post: operations["VendorsController_addVariant"];
  };
  "/vendor/products/{id}/variants/{variantId}": {
    patch: operations["VendorsController_updateVariant"];
  };
  "/vendor/products/{id}/images": {
    post: operations["VendorsController_addImages"];
  };
  "/products": {
    get: operations["CatalogController_listProducts"];
  };
  "/products/{id}": {
    get: operations["CatalogController_getProduct"];
  };
  "/categories": {
    get: operations["CatalogController_listCategories"];
  };
  "/tags": {
    get: operations["CatalogController_listTags"];
  };
  "/chat/threads": {
    get: operations["ChatController_listThreads"];
  };
  "/chat/threads/{orderId}/messages": {
    get: operations["ChatController_listMessages"];
    post: operations["ChatController_sendMessage"];
  };
  "/chat/threads/{orderId}/read": {
    patch: operations["ChatController_markRead"];
  };
  "/notifications": {
    get: operations["NotificationsController_list"];
  };
  "/notifications/{id}/read": {
    patch: operations["NotificationsController_markRead"];
  };
  "/notifications/read-all": {
    patch: operations["NotificationsController_markAllRead"];
  };
  "/cart": {
    get: operations["CartController_getCart"];
  };
  "/cart/items": {
    post: operations["CartController_addItem"];
  };
  "/cart/items/{id}": {
    delete: operations["CartController_removeItem"];
    patch: operations["CartController_updateItem"];
  };
  "/orders": {
    get: operations["OrdersController_list"];
    post: operations["OrdersController_create"];
  };
  "/orders/{id}": {
    get: operations["OrdersController_get"];
  };
  "/orders/{id}/status": {
    patch: operations["OrdersController_updateStatus"];
  };
  "/payments/stripe/checkout": {
    post: operations["PaymentsController_stripeCheckout"];
  };
  "/payments/wave/checkout": {
    post: operations["PaymentsController_waveCheckout"];
  };
  "/payments/kbzpay/checkout": {
    post: operations["PaymentsController_kbzCheckout"];
  };
  "/payments/stripe/webhook": {
    post: operations["PaymentsController_stripeWebhook"];
  };
  "/payments/wave/mock/webhook": {
    post: operations["PaymentsController_waveMockWebhook"];
  };
  "/payments/kbzpay/mock/webhook": {
    post: operations["PaymentsController_kbzpayMockWebhook"];
  };
  "/returns": {
    get: operations["ReturnsController_list"];
    post: operations["ReturnsController_create"];
  };
  "/returns/{id}/approve": {
    patch: operations["ReturnsController_approve"];
  };
  "/returns/{id}/reject": {
    patch: operations["ReturnsController_reject"];
  };
  "/returns/{id}/receive": {
    patch: operations["ReturnsController_receive"];
  };
  "/returns/{id}/refund": {
    patch: operations["ReturnsController_refund"];
  };
  "/reviews": {
    get: operations["ReviewsController_list"];
    post: operations["ReviewsController_create"];
  };
  "/promotions": {
    get: operations["PromotionsController_list"];
    post: operations["PromotionsController_create"];
  };
  "/promotions/validate": {
    post: operations["PromotionsController_validate"];
  };
  "/shipping/rates": {
    get: operations["ShippingController_listRates"];
  };
  "/shipping/pickup-locations": {
    get: operations["ShippingController_listPickupLocations"];
    post: operations["ShippingController_createPickupLocation"];
  };
  "/vendor/shipping/rates": {
    get: operations["VendorShippingController_listRates"];
    post: operations["VendorShippingController_createRate"];
  };
  "/vendor/shipping/rates/{id}": {
    delete: operations["VendorShippingController_disableRate"];
    patch: operations["VendorShippingController_updateRate"];
  };
  "/admin/vendors": {
    get: operations["AdminController_listVendors"];
  };
  "/admin/vendors/{id}/approve": {
    patch: operations["AdminController_approveVendor"];
  };
  "/admin/tags": {
    post: operations["AdminController_createTag"];
  };
  "/admin/tags/{id}": {
    patch: operations["AdminController_updateTag"];
  };
  "/admin/categories": {
    post: operations["AdminController_createCategory"];
  };
  "/admin/categories/{id}": {
    patch: operations["AdminController_updateCategory"];
  };
  "/admin/shipping/rates/{id}": {
    patch: operations["AdminController_updateShippingRate"];
  };
  "/uploads/presign": {
    post: operations["UploadsController_presign"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    RegisterDto: {
      email: string;
      password: string;
      /** @enum {string} */
      role?: "CUSTOMER" | "VENDOR" | "ADMIN";
      locale?: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    VerifyEmailDto: {
      token: string;
    };
    ResendVerificationDto: {
      email: string;
    };
    ApplyVendorDto: {
      name: string;
      /** @example US */
      country: string;
      /** @example USD */
      currency: string;
      /** @default 10 */
      commissionPct?: number;
    };
    CreateProductDto: {
      title: string;
      description: string;
      categoryId: string;
      tagIds?: string[];
    };
    UpdateProductDto: {
      title?: string;
      description?: string;
      categoryId?: string;
      tagIds?: string[];
      /** @enum {string} */
      status?: "DRAFT" | "ACTIVE" | "ARCHIVED";
    };
    VariantOptionDto: {
      name: string;
      value: string;
    };
    CreateVariantDto: {
      sku: string;
      options: components["schemas"]["VariantOptionDto"][];
      price: number;
      currency: string;
      stockQty: number;
      weightG?: number;
    };
    UpdateVariantDto: {
      sku?: string;
      options?: components["schemas"]["VariantOptionDto"][];
      price?: number;
      currency?: string;
      stockQty?: number;
      weightG?: number;
    };
    ProductImageInputDto: {
      url: string;
      altText?: string;
      sortOrder?: number;
    };
    AddProductImagesDto: {
      images: components["schemas"]["ProductImageInputDto"][];
    };
    SendChatMessageDto: {
      body: string;
    };
    MarkChatReadDto: {
      messageId?: string;
    };
    AddCartItemDto: {
      variantId: string;
      qty: number;
    };
    UpdateCartItemDto: {
      qty: number;
    };
    CreateOrderDto: {
      /** @enum {string} */
      fulfillment: "SHIPPING" | "PICKUP";
      shippingAddrId?: string;
      pickupLocId?: string;
    };
    UpdateOrderStatusDto: {
      /** @enum {string} */
      status: "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "PACKED" | "SHIPPED" | "READY_FOR_PICKUP" | "DELIVERED" | "PICKED_UP" | "RETURN_REQUESTED" | "RETURN_APPROVED" | "RETURNED" | "REFUNDED" | "CANCELED";
    };
    StripeCheckoutDto: {
      orderId: string;
    };
    MockPaymentWebhookDto: {
      orderId?: string;
      paymentId?: string;
      providerRef?: string;
    };
    CreateReturnDto: {
      orderId: string;
      reason: string;
    };
    UpdateReturnStatusDto: {
      notes?: string;
    };
    CreateReviewDto: {
      orderItemId: string;
      /** @example 5 */
      rating: number;
      comment?: string;
    };
    CreatePromotionDto: {
      /** @example ECO10 */
      code: string;
      /**
       * @example PERCENT
       * @enum {string}
       */
      type: "PERCENT" | "FIXED";
      /**
       * @description Percent(0-100) or fixed amount
       * @example 10
       */
      amount: number;
      /** @example 2026-01-01T00:00:00.000Z */
      startsAt: string;
      /** @example 2026-12-31T23:59:59.999Z */
      endsAt: string;
      /** @example 5000 */
      minOrder?: number;
    };
    ValidatePromotionDto: {
      /** @example ECO10 */
      code: string;
      /**
       * @description Order total in smallest unit
       * @example 10000
       */
      orderTotal: number;
      /** @description Vendor id to validate vendor-specific promotions */
      vendorId?: string;
    };
    CreatePickupLocationDto: {
      name: string;
      line1: string;
      city: string;
      state?: string;
      country: string;
      hours?: string;
    };
    CreateShippingRateDto: {
      /** @example US */
      country: string;
      /** @example USD */
      currency: string;
      /**
       * @description Flat shipping fee in smallest unit
       * @example 1299
       */
      flatRate: number;
      /** @default true */
      active?: boolean;
    };
    UpdateShippingRateDto: {
      /** @example US */
      country?: string;
      /** @example USD */
      currency?: string;
      /** @example 1299 */
      flatRate?: number;
      active?: boolean;
    };
    CreateTagDto: {
      name: string;
      slug: string;
      description?: string;
      /** @default true */
      active?: boolean;
    };
    UpdateTagDto: {
      name?: string;
      slug?: string;
      description?: string;
      active?: boolean;
    };
    CreateCategoryDto: {
      name: string;
      slug: string;
      parentId?: string;
    };
    UpdateCategoryDto: {
      name?: string;
      slug?: string;
      parentId?: string;
    };
    UpdateShippingRateAdminDto: {
      active: boolean;
    };
    PresignUploadDto: {
      filename: string;
      contentType: string;
      size: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_refresh: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_verifyEmail: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_resend: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendVerificationDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  UsersController_me: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorsController_apply: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyVendorDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  VendorsController_listProducts: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorsController_createProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProductDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  VendorsController_updateProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProductDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorsController_addVariant: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVariantDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  VendorsController_updateVariant: {
    parameters: {
      path: {
        id: string;
        variantId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateVariantDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorsController_addImages: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddProductImagesDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  CatalogController_listProducts: {
    parameters: {
      query?: {
        q?: string;
        categoryId?: string;
        tagIds?: string[];
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CatalogController_getProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CatalogController_listCategories: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CatalogController_listTags: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_listThreads: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_listMessages: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      path: {
        orderId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_sendMessage: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendChatMessageDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_markRead: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MarkChatReadDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationsController_list: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
        unreadOnly?: boolean;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationsController_markRead: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationsController_markAllRead: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_getCart: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_addItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddCartItemDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  CartController_removeItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_updateItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCartItemDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrdersController_list: {
    parameters: {
      query?: {
        status?: "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "PACKED" | "SHIPPED" | "READY_FOR_PICKUP" | "DELIVERED" | "PICKED_UP" | "RETURN_REQUESTED" | "RETURN_APPROVED" | "RETURNED" | "REFUNDED" | "CANCELED";
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrdersController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrdersController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrdersController_updateStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderStatusDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PaymentsController_stripeCheckout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StripeCheckoutDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_waveCheckout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StripeCheckoutDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_kbzCheckout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StripeCheckoutDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_stripeWebhook: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_waveMockWebhook: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MockPaymentWebhookDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_kbzpayMockWebhook: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MockPaymentWebhookDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ReturnsController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReturnsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateReturnDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ReturnsController_approve: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateReturnStatusDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReturnsController_reject: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateReturnStatusDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReturnsController_receive: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateReturnStatusDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReturnsController_refund: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateReturnStatusDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewsController_list: {
    parameters: {
      query?: {
        productId?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateReviewDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PromotionsController_list: {
    parameters: {
      query?: {
        vendorId?: string;
        /** @description Filter active promotions at current time */
        active?: boolean;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PromotionsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePromotionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PromotionsController_validate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidatePromotionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ShippingController_listRates: {
    parameters: {
      query?: {
        vendorId?: string;
        country?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ShippingController_listPickupLocations: {
    parameters: {
      query?: {
        vendorId?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ShippingController_createPickupLocation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePickupLocationDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  VendorShippingController_listRates: {
    parameters: {
      query?: {
        country?: string;
        active?: boolean;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorShippingController_createRate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateShippingRateDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  VendorShippingController_disableRate: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VendorShippingController_updateRate: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateShippingRateDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminController_listVendors: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminController_approveVendor: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminController_createTag: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTagDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminController_updateTag: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTagDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminController_createCategory: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCategoryDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminController_updateCategory: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCategoryDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminController_updateShippingRate: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateShippingRateAdminDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  UploadsController_presign: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresignUploadDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
}
